/**
 * Nomes para Layout de Corte PRO: <prefixoCaixa>_<prefixoPeca>.
 * Prefixo de peça = SSOT `resolvePieceToken` (sem tabelas paralelas).
 * Não altera medidas — apenas o campo `nome` na lista passada a cutlistToPieces.
 */

import { resolvePieceToken } from "../naming/industrialNaming";

function sanitizeToken(s: string): string {
  return s.replace(/[^A-Za-z0-9]+/g, "").replace(/^[-_]+|[-_]+$/g, "") || "X";
}

/** Heurística alinhada a nomes NP… gerados em projectState.formatAutoProjectName. */
export function isLikelyAutoGeneratedProjectName(projectName: string): boolean {
  const t = projectName.trim();
  if (t.length < 4) return false;
  if (!t.toUpperCase().startsWith("NP")) return false;
  const rest = t.slice(2);
  return /^[0-9]+[a-z0-9]*$/i.test(rest);
}

/** Primeira letra da primeira palavra + último grupo de dígitos no nome da caixa. */
export function prefixFromBoxDisplayName(boxNome: string): string | null {
  const t = boxNome.trim();
  if (!t) return null;
  const firstWord = t.split(/\s+/)[0] ?? "";
  const letterMatch = firstWord.match(/[A-Za-zÀ-ÿ]/u);
  if (!letterMatch) return null;
  const letter = letterMatch[0].toUpperCase();
  const nums = t.match(/\d+/g);
  const num = nums?.[nums.length - 1];
  if (!num) return null;
  return `${letter}${num}`;
}

function prefixFromCustomProjectName(projectName: string): string {
  const normalized = projectName.normalize("NFD").replace(/[\u0300-\u036f]/g, "");
  const lettersOnly = normalized.replace(/[^A-Za-z]/g, "");
  if (lettersOnly.length >= 3) return lettersOnly.slice(0, 3).toUpperCase();
  if (lettersOnly.length === 2) return lettersOnly.toUpperCase();
  if (lettersOnly.length === 1) return lettersOnly.toUpperCase();
  return "PRJ";
}

export function buildBoxPrefixForCutLayoutPro(boxNome: string | undefined, projectName: string): string {
  const pn = (projectName ?? "").trim() || "Projeto";
  const fromBox = boxNome != null && boxNome.trim() !== "" ? prefixFromBoxDisplayName(boxNome) : null;
  if (fromBox) return sanitizeToken(fromBox);

  if (isLikelyAutoGeneratedProjectName(pn)) {
    return sanitizeToken(pn);
  }
  return sanitizeToken(prefixFromCustomProjectName(pn));
}

export function piecePrefixForCutLayoutPro(item: { nome?: string; tipo?: string }): string {
  const tipo = String(item.tipo ?? "").trim();
  if (tipo) return resolvePieceToken(tipo);
  const nome = String(item.nome ?? "").trim();
  if (nome) return resolvePieceToken(nome);
  return "peca";
}

export function buildCutLayoutProPartName(
  item: { nome?: string; tipo?: string },
  boxNome: string | undefined,
  projectName: string
): string {
  const boxPrefix = buildBoxPrefixForCutLayoutPro(boxNome, projectName);
  const piecePrefix = piecePrefixForCutLayoutPro(item);
  return `${boxPrefix}_${piecePrefix}`;
}

export type BoxNomeLookup = ReadonlyMap<string, string> | Record<string, string>;

export function cutlistItemsWithCutLayoutProNames<T extends { nome?: string; tipo?: string; boxId?: string }>(
  items: T[],
  projectName: string,
  boxNomeLookup: BoxNomeLookup
): T[] {
  const getNome = (boxId: string): string | undefined => {
    if (boxNomeLookup instanceof Map) return boxNomeLookup.get(boxId);
    return boxNomeLookup[boxId];
  };
  return items.map((item) => {
    const meta = item as T & { metadata?: { industrialLabel?: string } };
    const industrialLabel = meta.metadata?.industrialLabel?.trim();
    if (industrialLabel) {
      return { ...item, nome: industrialLabel };
    }
    const boxId = String(item.boxId ?? "").trim();
    const boxNome = boxId ? getNome(boxId) : undefined;
    return { ...item, nome: buildCutLayoutProPartName(item, boxNome, projectName) };
  });
}

export function buildBoxNomeByIdFromBoxes(boxes: ReadonlyArray<{ id: string; nome?: string }>): Record<string, string> {
  const out: Record<string, string> = {};
  for (const b of boxes) {
    if (b?.id) out[b.id] = typeof b.nome === "string" ? b.nome : "";
  }
  return out;
}
