/**
 * Labels PT do Relatorio Final.
 * Source ASCII-only com escapes Unicode -> UTF-8 correto em runtime, sem mojibake.
 */

export const R = {
  titulo: "Relat\u00f3rio Final do Projeto",
  tituloCurto: "Relat\u00f3rio Final",
  isolado: "Documento isolado \u2014 n\u00e3o altera o fluxo industrial.",
  dirty: " \u2014 Altera\u00e7\u00f5es por guardar",
  classico: "Estilo cl\u00e1ssico",
  cards: "Estilo cards",
  historico: "Hist\u00f3rico",
  historicoTitulo: "Hist\u00f3rico de altera\u00e7\u00f5es",
  historicoHint: "Registo local das edi\u00e7\u00f5es manuais do relat\u00f3rio (mais recentes primeiro).",
  semAlteracoes: "Sem altera\u00e7\u00f5es registadas ainda.",
  imprimir: "Imprimir",
  exportarPdf: "Exportar PDF",
  guardar: "Guardar altera\u00e7\u00f5es",
  aGuardar: "A guardar...",
  guardadoServidor: "Altera\u00e7\u00f5es guardadas no servidor.",
  guardarFail: "Falha ao guardar no servidor.",
  overrideGuardadoOk: "Override aplicado e guardado.",
  email: "Enviar por email",
  voltar: "Voltar",
  carregar: "A carregar relat\u00f3rio final...",
  indisponivel: "Relat\u00f3rio indispon\u00edvel.",
  guardado: "Altera\u00e7\u00f5es guardadas no relat\u00f3rio.",
  pdfOk: "PDF exportado.",
  pdfFail: "Falha ao exportar PDF.",
  emailTitulo: "Enviar relat\u00f3rio por email",
  emailHint: "Indique o email do destinat\u00e1rio. O PDF do relat\u00f3rio ser\u00e1 enviado em anexo.",
  emailDestinatario: "Email do destinat\u00e1rio",
  emailObrigatorio: "Indique o email do destinat\u00e1rio.",
  emailInvalido: "Email com formato inv\u00e1lido.",
  emailPlaceholder: "destinatario@exemplo.com",
  emailEnviar: "Enviar",
  emailAEnviar: "A gerar PDF e a enviar...",
  emailOk: "Relat\u00f3rio enviado por email.",
  emailFail: "N\u00e3o foi poss\u00edvel enviar o relat\u00f3rio por email.",

  infoGerais: "1. Informa\u00e7\u00f5es gerais do projeto",
  designer: "Designer",
  nomeProjeto: "Nome do projeto",
  empresa: "Empresa executora",
  materiaisDescricao: "Materiais",
  dataInicioExec: "Data in\u00edcio execu\u00e7\u00e3o",
  dataFimExec: "Data conclus\u00e3o execu\u00e7\u00e3o",

  painelGrafico: "2. Painel gr\u00e1fico (resumo visual)",
  tarefasConcluidas: "Tarefas conclu\u00eddas",
  erros: "Erros",
  errosCorrigidos: "Erros corrigidos",
  melhorias: "Melhorias",
  melhoriasAplicadas: "Melhorias aplicadas",
  ordensTrabalho: "Ordens de trabalho",
  colaboradores: "Colaboradores",
  tempoTrabalho: "Tempo de trabalho",
  solucaoAplicada: "Solu\u00e7\u00e3o aplicada",
  melhoriaProposta: "Melhoria proposta",
  melhoriaImplementada: "Melhoria implementada",
  registoFeedback: "Erros, solu\u00e7\u00f5es e melhorias",
  adicionar: "Adicionar",
  excluir: "Excluir",
  semItens: "Sem itens.",
  novoItem: "Novo item",
  editarItem: "Editar item",
  errosMontagem: "Erros na Montagem",
  operadoresFunc: "Operadores / funcion\u00e1rios",
  materiaisHintFerragens:
    "Ferragens do projeto (fonte \u00fanica da linha Ferragens no Financeiro).",
  adicionarChapa: "Adicionar chapa",
  escolherChapa: "Escolher chapa do catálogo",
  espessura: "Espessura",
  medida: "Medida",
  comprimentoMm: "Comprimento (mm)",
  larguraMm: "Largura (mm)",
  precoChapa: "\u20ac/chapa",
  precoPorMetroEur: "Preço por metro (€/m)",
  precoTotal: "Preço total",
  precoM2: "\u20ac/m\u00b2",
  areaChapaM2: "Área da chapa (m²)",
  precoCalcM2: "Preço calculado por m²",
  tipoOrla: "Tipo da orla",
  quantidadeM: "Quantidade (m)",
  precoPorMetro: "Preço por metro",


  estadoProjeto: "3. Estado do projeto (Design / Produ\u00e7\u00e3o / Montagem)",
  design: "3.1 Design",
  inicioDesign: "In\u00edcio design",
  conclusaoDesign: "Conclus\u00e3o design",
  revisoesAntes: "Revis\u00f5es antes produ\u00e7\u00e3o",
  revisoesApos: "Revis\u00f5es ap\u00f3s produ\u00e7\u00e3o",
  errosDesign: "Erros de design",
  solucoes: "Solu\u00e7\u00f5es aplicadas",
  melhoriasPropostas: "Melhorias propostas",
  melhoriasImpl: "Melhorias implementadas",

  producao: "3.2 Produ\u00e7\u00e3o",
  operadores: "Operadores / funcion\u00e1rios",
  totalCaixas: "Total de caixas",
  totalPecas: "Total de pe\u00e7as",
  inicioProducao: "In\u00edcio produ\u00e7\u00e3o",
  fimProducao: "Fim produ\u00e7\u00e3o",
  horasEfetivas: "Horas efetivas",
  reProducoes: "Re-produ\u00e7\u00f5es",
  errosProducao: "Erros na produ\u00e7\u00e3o",
  listaCaixas: "Lista de caixas",
  listaPecas: "Lista de pe\u00e7as (formato t\u00e9cnico)",
  semCaixas: "Sem caixas no projeto.",
  peca: "PE\u00c7A",
  dimensoes: "Dimens\u00f5es",
  tipo: "Material",
  nome: "Nome",
  erro: "Erro",
  notas: "Notas",
  correcao: "Corre\u00e7\u00e3o",

  montagem: "3.3 Montagem / Instala\u00e7\u00e3o",
  dataEnvio: "Data de envio",
  instaladores: "Marceneiros / instaladores",
  inicioMontagem: "In\u00edcio montagem",
  fimMontagem: "Fim montagem",
  intervencoes: "Interven\u00e7\u00f5es p\u00f3s-montagem",
  adicionarPessoa: "Adicionar pessoa",
  remover: "Remover",
  fechar: "Fechar",
  horas: "Horas",
  tarefas: "Tarefas",

  materiais: "4. Materiais / ferragens / consumos",
  materiaisHint:
    "Dados iniciais de ferragens_totais. Edições ficam só no relatório.",
  quantidade: "Quantidade",
  observacoes: "Observações",
  substituicao: "Substituição",
  adicionarLinha: "Adicionar linha",
  semMateriais: "Sem materiais. Adicione linhas manualmente ou abra um projeto com ferragens.",

  financeiro: "4. Financeiro (custos din\u00e2micos)",
  financeiroHint:
    "Totais oficiais = \u00faltima gera\u00e7\u00e3o TCN (\u00abGerar arquivo completo\u00bb). ADMIN Custos continua a ser o or\u00e7amento live do projeto aberto.",
  financeiroSemRelease:
    "Ainda n\u00e3o existe snapshot da \u00faltima gera\u00e7\u00e3o TCN. Execute \u00abGerar arquivo completo\u00bb para preencher o Financeiro do Relat\u00f3rio. O or\u00e7amento live continua dispon\u00edvel em ADMIN \u2192 Custos.",
  financeiroParcialHint:
    "Nesta vers\u00e3o o total inclui apenas Pain\u00e9is (TCN) e Ferragens. Orla, m\u00e3o de obra, desperd\u00edcio, serragem, log\u00edstica e restantes linhas entram numa fase seguinte \u2014 este total ainda n\u00e3o \u00e9 o custo completo do projeto.",
  custoChapasReais: "Custo total das chapas",
  mostrarDetalheCustos: "Mostrar detalhe de custos",
  ocultarDetalheCustos: "Ocultar detalhe de custos",
  ivaPct: "IVA (%)",
  linha: "Linha",
  origem: "Origem",
  ajusteManual: "Ajuste manual",
  ajusteManualHint:
    "Override opcional. Deixe vazio para usar o valor oficial (SSOT).",
  overrideManual: "override manual",
  badgeOverride: "override",
  badgeOverrideSuspeito: "override · possível eco sticky",
  badgeValorOficial: "valor oficial",
  tooltipOrigemPreco: "Origem do pre\u00e7o oficial (Unificado / chapas reais).",
  tooltipValorOficial: "Total oficial do Financeiro ADMIN (SSOT).",
  tooltipOverride: "Override manual activo na camada visual.",
  tooltipOverrideSuspeito:
    "Este override coincide com a soma do detalhe antigo (poss\u00edvel eco sticky). N\u00e3o foi removido automaticamente \u2014 use \u00abRepor ao oficial\u00bb se n\u00e3o for intencional.",
  reporAoOficial: "Repor ao oficial",
  reporAoOficialHint:
    "Remove o override desta linha e volta ao total SSOT (Unificado).",
  tooltipTotalVisual: "Soma do detalhe edit\u00e1vel (n\u00e3o \u00e9 o SSOT).",
  totalVisual: "Total visual",
  totalVisualChapas: "\u20ac/total chapas",
  substituirMaterial: "Substituir material",
  adicionarItem: "Adicionar item",
  aplicarVisualOverride: "Aplicar total visual como override",
  aplicarVisualOverrideHint:
    "Copia a soma do detalhe para o override da linha e grava no servidor. O SSOT Unificado permanece intacto.",
  precoUnit: "Pre\u00e7o unit\u00e1rio",
  total: "Total",
  subtotal: "Subtotal",
  detalhe: "Detalhe",
  adicionarTipo: "Adicionar tipo",
  preco: "Pre\u00e7o",
  totalSsot: "Total oficial (SSOT)",
  paineisAccordionHint:
    "Lista edit\u00e1vel de chapas (camada visual). O total oficial de Pain\u00e9is vem do Unificado.",
  semChapasNesting: "Sem chapas. Adicione manualmente ou abra um projeto com nesting real.",
  areaM2: "\u00c1rea (m\u00b2)",
  adicionarFerragem: "Adicionar ferragem",
  adicionarDoCatalogo: "Adicionar do cat\u00e1logo",
  adicionarManualmente: "Adicionar manualmente",
  escolherFerragem: "Escolher ferragem do cat\u00e1logo",
  escolherChapaCatalogo: "Escolher chapa do cat\u00e1logo",
  nomeOuCatalogo: "Nome ou escolher da lista",
  nomeFerragem: "Nome da ferragem",
  ferragensAccordionHint:
    "Lista edit\u00e1vel de ferragens (camada visual). O total oficial vem do Unificado.",
  semFerragens: "Sem ferragens. Adicione manualmente ou abra um projeto com ferragens.",
  substituirFerragem: "Substituir ferragem",
  tooltipOrigemPrecoFerragem: "Origem do pre\u00e7o (cat\u00e1logo B / fallback A / Unificado / override).",

  notasProjeto: "5. Notas do Projeto",
  adicionarNota: "Adicionar nota",
  editarNota: "Editar nota",
  novaNota: "Nova nota",
  editar: "Editar",
  cancelar: "Cancelar",
  guardarNota: "Guardar",
  autor: "Autor",
  texto: "Texto",
  semNotas: "Sem notas internas.",

  qualidade: "6. Avalia\u00e7\u00e3o de Qualidade",
  estrelas: "estrelas",
  novaObservacao: "Nova observa\u00e7\u00e3o",
  adicionarObservacao: "Adicionar observa\u00e7\u00e3o",
  semObservacoes: "Sem observa\u00e7\u00f5es de qualidade.",
  star: "\u2605",

  resumo: "7. Resumo final (Total do projeto)",
  caixas: "Caixas",
  pecas: "Pe\u00e7as",
  modulos: "M\u00f3dulos",
  portasCount: "Portas",
  gavetasCount: "Gavetas",
  materiaisFerragens: "Materiais / ferragens",
  qualidadeLabel: "Qualidade",
  totalProjeto: "Total do projeto",

  margemGanho: "Margem de ganho",
  margemGanhoHint: "Relatório — não altera o Unificado ADMIN",
  margemGanhoModo: "Modo da margem (% ou €)",
  margemGanhoValor: "Valor da margem",

  paineisTitulo: "Pain\u00e9is (chapas reais)",
  paineisHint:
    "Contagem oficial = nesting PRO/TCN (quando j\u00e1 gerado). Sem TCN: estimativa r\u00e1pida \u2014 pode diferir do TCN final. Totais oficiais no Financeiro Unificado.",
  semChapas: "Sem chapas. Adicione do cat\u00e1logo ou abra um projeto com nesting real.",
  totalChapas: "Total das chapas",
  totalUnificadoMadeira: "Refer\u00eancia Unificado (madeira)",

  campo: "Campo",
  antes: "Antes",
  depois: "Depois",
  data: "Data",
  utilizador: "Utilizador",
} as const;
