/**
 * Labels PT do Relatorio Final.
 * Source ASCII-only com escapes Unicode -> UTF-8 correto em runtime, sem mojibake.
 */

export const R = {
  titulo: "Relat\u00f3rio Final do Projeto",
  tituloCurto: "Relat\u00f3rio Final",
  isolado: "Documento isolado \u2014 n\u00e3o altera o fluxo industrial.",
  dirty: " \u2014 Altera\u00e7\u00f5es por guardar",
  classico: "Estilo cl\u00e1ssico",
  cards: "Estilo cards",
  historico: "Hist\u00f3rico",
  historicoTitulo: "Hist\u00f3rico de altera\u00e7\u00f5es",
  historicoHint: "Registo local das edi\u00e7\u00f5es manuais do relat\u00f3rio (mais recentes primeiro).",
  semAlteracoes: "Sem altera\u00e7\u00f5es registadas ainda.",
  imprimir: "Imprimir",
  exportarPdf: "Exportar PDF",
  guardar: "Guardar altera\u00e7\u00f5es",
  aGuardar: "A guardar...",
  email: "Enviar por email",
  voltar: "Voltar",
  carregar: "A carregar relat\u00f3rio final...",
  indisponivel: "Relat\u00f3rio indispon\u00edvel.",
  guardado: "Altera\u00e7\u00f5es guardadas no relat\u00f3rio.",
  pdfOk: "PDF exportado.",
  pdfFail: "Falha ao exportar PDF.",

  infoGerais: "1. Informa\u00e7\u00f5es gerais do projeto",
  designer: "Designer",
  nomeProjeto: "Nome do projeto",
  empresa: "Empresa executora",
  materiaisDescricao: "Materiais",
  dataInicioExec: "Data in\u00edcio execu\u00e7\u00e3o",
  dataFimExec: "Data conclus\u00e3o execu\u00e7\u00e3o",

  painelGrafico: "2. Painel gr\u00e1fico (resumo visual)",
  tarefasConcluidas: "Tarefas conclu\u00eddas",
  erros: "Erros",
  errosCorrigidos: "Erros corrigidos",
  melhorias: "Melhorias",
  melhoriasAplicadas: "Melhorias aplicadas",
  ordensTrabalho: "Ordens de trabalho",
  colaboradores: "Colaboradores",
  tempoTrabalho: "Tempo de trabalho",
  adicionar: "Adicionar",
  excluir: "Excluir",
  semItens: "Sem itens.",
  novoItem: "Novo item",
  editarItem: "Editar item",
  errosMontagem: "Erros na Montagem",
  operadoresFunc: "Operadores / funcion\u00e1rios",
  materiaisHintFerragens:
    "Ferragens do projeto (fonte \u00fanica da linha Ferragens no Financeiro).",
  adicionarChapa: "Adicionar chapa",
  escolherChapa: "Escolher chapa do cat\u00e1logo",
  espessura: "Espessura",
  medida: "Medida",
  precoChapa: "Pre\u00e7o da chapa",
  precoTotal: "Pre\u00e7o total",
  precoM2: "Pre\u00e7o do m\u00b2",
  areaChapaM2: "\u00c1rea da chapa (m\u00b2)",
  precoCalcM2: "Pre\u00e7o calculado por m\u00b2",


  estadoProjeto: "3. Estado do projeto (Design / Produ\u00e7\u00e3o / Montagem)",
  design: "3.1 Design",
  inicioDesign: "In\u00edcio design",
  conclusaoDesign: "Conclus\u00e3o design",
  revisoesAntes: "Revis\u00f5es antes produ\u00e7\u00e3o",
  revisoesApos: "Revis\u00f5es ap\u00f3s produ\u00e7\u00e3o",
  errosDesign: "Erros de design",
  solucoes: "Solu\u00e7\u00f5es aplicadas",
  melhoriasPropostas: "Melhorias propostas",
  melhoriasImpl: "Melhorias implementadas",

  producao: "3.2 Produ\u00e7\u00e3o",
  operadores: "Operadores / funcion\u00e1rios",
  totalCaixas: "Total de caixas",
  totalPecas: "Total de pe\u00e7as",
  inicioProducao: "In\u00edcio produ\u00e7\u00e3o",
  fimProducao: "Fim produ\u00e7\u00e3o",
  horasEfetivas: "Horas efetivas",
  reProducoes: "Re-produ\u00e7\u00f5es",
  errosProducao: "Erros na produ\u00e7\u00e3o",
  listaCaixas: "Lista de caixas",
  listaPecas: "Lista de pe\u00e7as (formato t\u00e9cnico)",
  semCaixas: "Sem caixas no projeto.",
  peca: "PE\u00c7A",
  dimensoes: "Dimens\u00f5es",
  tipo: "Tipo",
  nome: "Nome",
  erro: "Erro",
  notas: "Notas",
  correcao: "Corre\u00e7\u00e3o",

  montagem: "3.3 Montagem / Instala\u00e7\u00e3o",
  dataEnvio: "Data de envio",
  instaladores: "Marceneiros / instaladores",
  inicioMontagem: "In\u00edcio montagem",
  fimMontagem: "Fim montagem",
  intervencoes: "Interven\u00e7\u00f5es p\u00f3s-montagem",
  adicionarPessoa: "Adicionar pessoa",
  remover: "Remover",
  fechar: "Fechar",
  horas: "Horas",
  tarefas: "Tarefas",

  materiais: "4. Materiais / ferragens / consumos",
  materiaisHint:
    "Dados iniciais de ferragens_totais. Edi\u00e7\u00f5es ficam s\u00f3 no relat\u00f3rio.",
  quantidade: "Quantidade",
  observacoes: "Observa\u00e7\u00f5es",
  substituicao: "Substitui\u00e7\u00e3o",
  adicionarLinha: "Adicionar linha",
  semMateriais: "Sem materiais. Adicione linhas manualmente ou abra um projeto com ferragens.",

  financeiro: "5. Financeiro (custos din\u00e2micos)",
  financeiroHint:
    "Isolado do m\u00f3dulo Custos ADMIN. Totais recalculam a partir de quantidade e pre\u00e7o.",
  ivaPct: "IVA (%)",
  linha: "Linha",
  precoUnit: "Pre\u00e7o unit\u00e1rio",
  total: "Total",
  subtotal: "Subtotal",
  detalhe: "Detalhe",
  adicionarTipo: "Adicionar tipo",
  preco: "Pre\u00e7o",

  notasProjeto: "7. Notas do Projeto",
  adicionarNota: "Adicionar nota",
  editarNota: "Editar nota",
  novaNota: "Nova nota",
  editar: "Editar",
  cancelar: "Cancelar",
  guardarNota: "Guardar",
  autor: "Autor",
  texto: "Texto",
  semNotas: "Sem notas internas.",

  qualidade: "8. Avalia\u00e7\u00e3o de Qualidade",
  estrelas: "estrelas",
  novaObservacao: "Nova observa\u00e7\u00e3o",
  adicionarObservacao: "Adicionar observa\u00e7\u00e3o",
  semObservacoes: "Sem observa\u00e7\u00f5es de qualidade.",
  star: "\u2605",

  resumo: "9. Resumo final (Total do projeto)",
  caixas: "Caixas",
  pecas: "Pe\u00e7as",
  materiaisFerragens: "Materiais / ferragens",
  qualidadeLabel: "Qualidade",
  totalProjeto: "Total do projeto",

  campo: "Campo",
  antes: "Antes",
  depois: "Depois",
  data: "Data",
  utilizador: "Utilizador",
} as const;
