/**
 * API stub segura do Viewer — contrato de inicialização.
 * PimoViewerProvider expõe sempre este objeto (ou API real registada) — nunca null.
 * viewerReady permanece false até ViewerCore.notifyViewerReady().
 */
import type { PimoViewerApi } from "./PimoViewerContextCore";

/** Stubs NOOP — API segura antes do ViewerCore estar montado. */
export const PIMO_VIEWER_STUBS: Record<string, unknown> = {
  setPanelEdgesVisible: () => {},
  setAllPanelsHidden: () => {},
  setHiddenPanels: () => {},
  setPanelHidden: () => {},
  setPanelRenderingEnabled: () => {},
  getPanelRenderingEnabled: () => false,
  setRoomCeilingVisible: () => {},
  setRoomFloorMode: () => {},
  setRoomHiddenWalls: () => {},
  setRoomUtilities: () => {},
  setWallEditMode: () => {},
  setMousePreset: () => {},
  setBackgroundMode: () => {},
  getBackgroundMode: () => "studio" as const,
  setMaterialQuality: () => {},
  setReflectionsEnabled: () => {},
  setGlossIntensity: () => {},
  getGlossIntensity: () => 1,
  setMatteMode: () => {},
  getMatteMode: () => false,
  setPhotoModeEnabled: () => {},
  setMode: () => {},
  setShowcaseMode: () => {},
  getCurrentMode: () => "performance" as const,
  getShowcaseMode: () => false,
  setExplodedViewEnabled: () => {},
  setExplodedViewIntensity: () => {},
  setHighlightEnabled: () => {},
  setUltraPerformanceModeOptions: () => {},
  setUltraPerformanceMode: () => {},
  setGlobalLightIntensity: () => {},
  getGlobalLightIntensity: () => 1,
  setShadowIntensity: () => {},
  getShadowIntensity: () => 1,
  getBoxIdByMesh: () => null,
  projectWorldToScreen: () => null,
  getSelectedBoxDepthAxisWorldSegment: () => null,
  getBoxIdAtPointerPublic: () => null,
  setMeasurementMode: () => {},
  getMeasurementMode: () => false,
  getInternalSelectionHit: () => null,
  getInternalSelection: () => null,
  setInternalSelection: () => {},
  setInternalSelectionEnabled: () => {},
  getInternalSelectionEnabled: () => false,
  setOnInternalSurfaceSelected: () => {},
  setOnInternalEdgeSelected: () => {},
  setOnInternalPointSelected: () => {},
  getInternalMeasurements: () => null,
  isInternalRulerOverlayActive: () => false,
  getSelectedObjects: () => [],
  align: () => false,
  getDimensionsOverlayData: () => [],
  getPrintReadyDimensions: () => ({ entries: [], generatedAt: 0 }),
  internalRuler: {
    enableForBox: () => {},
    disable: () => {},
    isActive: () => false,
    getLastMeasurement: () => null,
    getActiveBoxId: () => null,
    syncFromProject: () => {},
  },
  snapping: {
    enable: () => {},
    disable: () => {},
    isEnabled: () => false,
    setGridSize: () => {},
    setCaptureRadius: () => {},
    setMagnetStrength: () => {},
    setMode: () => {},
    getMode: () => "basic" as const,
    setRoomSnappingEnabled: () => {},
    isRoomSnappingEnabled: () => false,
    setAutoAlignmentEnabled: () => {},
    isAutoAlignmentEnabled: () => true,
    setAutoSpacingEnabled: () => {},
    isAutoSpacingEnabled: () => false,
    setWallOffset: () => {},
    getWallOffset: () => 0,
    getActiveAlignmentType: () => null,
  },
  autoLayout: {
    fillWallWithModule: () => false,
    extendAlongWallFromBox: () => false,
    distributeBoxesEvenly: () => false,
    autoStackShelvesInBox: () => false,
  },
  setIndustrialDesignWorkspaceEnabled: () => {},
  getIndustrialDesignWorkspaceEnabled: () => false,
  setIndustrialDesignActiveHoleType: () => {},
  getIndustrialDesignActiveHoleType: () => null,
  setIndustrialDesignBox: () => {},
  getIndustrialDesignBox: () => null,
  getIndustrialDesignSelectedPanelId: () => null,
  setOnIndustrialDesignPanelSelected: () => {},
  setOnIndustrialDesignHolePlaced: () => {},
  setOnIndustrialDesignChanged: () => {},
  setOnIndustrialDesignValidationChanged: () => {},
  setOnIndustrialDesignValidationFailed: () => {},
  getIndustrialDesignValidationIssues: () => [],
  refreshIndustrialDesignValidation: () => [],
  addBox: () => false,
  removeBox: () => false,
  updateBox: () => false,
  setBoxIndex: () => false,
  setBoxPosition: () => false,
  setBoxGap: () => {},
  addModelToBox: () => false,
  removeModelFromBox: () => false,
  clearModelsFromBox: () => {},
  listModels: () => null,
  getBoxDimensions: () => null,
  setOnBoxSelected: () => {},
  setTransformMode: () => {},
  syncOrlaVisuals: () => {},
  syncRemateVisuals: () => {},
  syncHematiVisuals: () => {},
  syncRodapeVisuals: () => {},
  refreshTransformControlsAttachment: () => {},
  resolveFinishCollisionAfterSync: () => {},
  getTransformControlsDragging: () => false,
  setMultiSelectionOutlines: () => {},
  setGroupTransformMembers: () => {},
  clearGroupTransformMembers: () => {},
  selectRemate: () => {},
  selectRodape: () => {},
  selectHemati: () => {},
  selectDivSep: () => {},
  isPointerOnSelectableObject: () => false,
  getSelectionIdsInScreenRect: () => [],
  getBoxWorldMatrix: () => null,
  getRemateMesh: () => null,
  applyRemateKeyboardTransform: () => false,
  addMeasurementAnchorAtPointer: () => null,
  syncMeasurementAnchors: () => {},
};

let sharedStubApi: PimoViewerApi | null = null;

/** API viewer segura (nunca null) para consumidores React antes do ViewerCore estar pronto. */
export function createPimoViewerStubApi(): PimoViewerApi {
  if (sharedStubApi) return sharedStubApi;
  sharedStubApi = {
    ...PIMO_VIEWER_STUBS,
    viewerRef: { current: null },
    viewerReady: false,
  } as PimoViewerApi;
  return sharedStubApi;
}

export function getPimoViewerStubApi(): PimoViewerApi {
  return createPimoViewerStubApi();
}
