import type { FC } from "react";
import type { IconName, IconProps } from "./types";
import {
  IconThemeSun,
  IconThemeMoon,
  IconUser,
  IconUpload,
  IconProjects,
  IconSettings,
} from "./groups/header";
import {
  IconHome,
  IconFurniture,
  IconModels,
  IconCalculator,
  IconElectro,
  IconAccessories,
  IconInfo,
} from "./groups/leftToolbar";
import {
  IconCamera,
  IconHighlight,
  IconRuler,
  IconGrid,
  IconRoom,
  IconOrbit,
  IconPan,
  IconSelect,
  IconMove,
  IconRotate,
  IconScale,
} from "./groups/viewer";
import {
  IconDelete,
  IconRename,
  IconDuplicate,
  IconLock,
  IconUnlock,
  IconAlignFront,
  IconAlignBottom,
  IconMaterial,
  IconMouse,
  IconChevronRight,
  IconCheck,
  IconClose,
} from "./groups/contextMenu";
import {
  IconUndo,
  IconRedo,
  IconPhotoMode,
  IconResetCamera,
  IconSend,
  IconDisplayMenu,
  IconDisplayCheck,
  IconLock3D,
  IconExploded,
} from "./groups/toolbar";
import {
  IconAdminWood,
  IconAdminChecklist,
  IconAdminScrew,
  IconAdminPuzzle,
  IconAdminRuler,
  IconAdminSettings,
  IconAdminBook,
  IconAdminFolder,
  IconAdminArchive,
  IconAdminLab,
  IconAdminTools,
  IconAdminTag,
  IconAdminSave,
  IconAdminChart,
  IconAdminDocs,
} from "./groups/admin";
import { IconAlertWarning, IconAlertInfo, IconAlertError, IconBell } from "./groups/alerts";
import { IconBlueprint } from "./groups/manufacturing";

export const iconRegistry: Record<IconName, FC<IconProps>> = {
  themeSun: IconThemeSun,
  themeMoon: IconThemeMoon,
  user: IconUser,
  upload: IconUpload,
  projects: IconProjects,
  settings: IconSettings,
  home: IconHome,
  furniture: IconFurniture,
  models: IconModels,
  calculator: IconCalculator,
  electro: IconElectro,
  accessories: IconAccessories,
  info: IconInfo,
  camera: IconCamera,
  highlight: IconHighlight,
  ruler: IconRuler,
  grid: IconGrid,
  room: IconRoom,
  orbit: IconOrbit,
  pan: IconPan,
  select: IconSelect,
  move: IconMove,
  rotate: IconRotate,
  scale: IconScale,
  delete: IconDelete,
  rename: IconRename,
  duplicate: IconDuplicate,
  lock: IconLock,
  unlock: IconUnlock,
  alignFront: IconAlignFront,
  alignBottom: IconAlignBottom,
  material: IconMaterial,
  mouse: IconMouse,
  chevronRight: IconChevronRight,
  check: IconCheck,
  close: IconClose,
  undo: IconUndo,
  redo: IconRedo,
  photoMode: IconPhotoMode,
  resetCamera: IconResetCamera,
  send: IconSend,
  displayMenu: IconDisplayMenu,
  displayCheck: IconDisplayCheck,
  lock3D: IconLock3D,
  exploded: IconExploded,
  adminWood: IconAdminWood,
  adminChecklist: IconAdminChecklist,
  adminScrew: IconAdminScrew,
  adminPuzzle: IconAdminPuzzle,
  adminRuler: IconAdminRuler,
  adminSettings: IconAdminSettings,
  adminBook: IconAdminBook,
  adminFolder: IconAdminFolder,
  adminArchive: IconAdminArchive,
  adminLab: IconAdminLab,
  adminTools: IconAdminTools,
  adminTag: IconAdminTag,
  adminSave: IconAdminSave,
  adminChart: IconAdminChart,
  adminDocs: IconAdminDocs,
  alertWarning: IconAlertWarning,
  alertInfo: IconAlertInfo,
  alertError: IconAlertError,
  bell: IconBell,
  blueprint: IconBlueprint,
};
