import type { BaseCabinetModel } from "./types";

/** Altura padrão base (mm). */
const BASE_HEIGHT_MM = 720;
/** Profundidade padrão base (mm). */
const BASE_DEPTH_MM = 600;

/**
 * Modelos base de armários (Base Cabinets).
 * Cada entrada é uma unidade individual; o sistema aplica espessura, costa, pés e regras 32mm.
 */
export const BASE_CABINET_MODELS: BaseCabinetModel[] = [
  {
    id: "base-200-garravera",
    nome: "A1 20cm 0 portas",
    widthMm: 200,
    heightMm: 800,
    depthMm: BASE_DEPTH_MM,
    doors: 0,
    shelves: 5,
    drawers: 0,
    categoria: "base",
  },
  {
    id: "base-300-porta-2prateleiras",
    nome: "A2 30cm 1 porta",
    widthMm: 300,
    heightMm: BASE_HEIGHT_MM,
    depthMm: BASE_DEPTH_MM,
    doors: 1,
    shelves: 2,
    drawers: 0,
    categoria: "base",
  },
  {
    id: "base-300-3gavetas",
    nome: "A3 30cm 3 gavetas",
    widthMm: 300,
    heightMm: BASE_HEIGHT_MM,
    depthMm: BASE_DEPTH_MM,
    doors: 0,
    shelves: 0,
    drawers: 3,
    categoria: "base",
  },
  {
    id: "base-400-3gavetas",
    nome: "A4 40cm 3 gavetas",
    widthMm: 400,
    heightMm: BASE_HEIGHT_MM,
    depthMm: BASE_DEPTH_MM,
    doors: 0,
    shelves: 0,
    drawers: 3,
    categoria: "base",
  },
  {
    id: "base-400-porta-3gavetas-2prateleiras",
    nome: "A5 40cm 3 gavetas",
    widthMm: 400,
    heightMm: BASE_HEIGHT_MM,
    depthMm: BASE_DEPTH_MM,
    doors: 1,
    shelves: 2,
    drawers: 3,
    categoria: "base",
  },
  {
    id: "base-500-3gavetas",
    nome: "A6 50cm 3 gavetas",
    widthMm: 500,
    heightMm: BASE_HEIGHT_MM,
    depthMm: BASE_DEPTH_MM,
    doors: 0,
    shelves: 0,
    drawers: 3,
    categoria: "base",
  },
  {
    id: "base-500-porta-2prateleiras",
    nome: "A7 50cm 1 porta",
    widthMm: 500,
    heightMm: BASE_HEIGHT_MM,
    depthMm: BASE_DEPTH_MM,
    doors: 1,
    shelves: 2,
    drawers: 0,
    categoria: "base",
  },
  {
    id: "base-600-2portas-2prateleiras",
    nome: "A8 60cm 2 portas",
    widthMm: 600,
    heightMm: BASE_HEIGHT_MM,
    depthMm: BASE_DEPTH_MM,
    doors: 2,
    shelves: 2,
    drawers: 0,
    categoria: "base",
  },
  {
    id: "base-600-3gavetas",
    nome: "A9 60cm 3 gavetas",
    widthMm: 600,
    heightMm: BASE_HEIGHT_MM,
    depthMm: BASE_DEPTH_MM,
    doors: 0,
    shelves: 0,
    drawers: 3,
    categoria: "base",
  },
  {
    id: "base-700-2portas-2prateleiras",
    nome: "A10 70cm 2 portas",
    widthMm: 700,
    heightMm: BASE_HEIGHT_MM,
    depthMm: BASE_DEPTH_MM,
    doors: 2,
    shelves: 2,
    drawers: 0,
    categoria: "base",
  },
  {
    id: "base-800-2portas-2prateleiras",
    nome: "A11 80cm 2 portas",
    widthMm: 800,
    heightMm: BASE_HEIGHT_MM,
    depthMm: BASE_DEPTH_MM,
    doors: 2,
    shelves: 2,
    drawers: 0,
    categoria: "base",
  },
  {
    id: "base-900-2portas-2prateleiras",
    nome: "A12 90cm 2 portas",
    widthMm: 900,
    heightMm: BASE_HEIGHT_MM,
    depthMm: BASE_DEPTH_MM,
    doors: 2,
    shelves: 2,
    drawers: 0,
    categoria: "base",
  },
  {
    id: "base-1000-2portas-2prateleiras",
    nome: "A13 100cm 2 portas",
    widthMm: 1000,
    heightMm: BASE_HEIGHT_MM,
    depthMm: BASE_DEPTH_MM,
    doors: 2,
    shelves: 2,
    drawers: 0,
    categoria: "base",
  },
  {
    id: "base-1100-2portas-2prateleiras",
    nome: "A14 110cm 2 portas",
    widthMm: 1100,
    heightMm: BASE_HEIGHT_MM,
    depthMm: BASE_DEPTH_MM,
    doors: 2,
    shelves: 2,
    drawers: 0,
    categoria: "base",
  },
  {
    id: "base-1200-2portas-2prateleiras",
    nome: "A15 120cm 2 portas",
    widthMm: 1200,
    heightMm: BASE_HEIGHT_MM,
    depthMm: BASE_DEPTH_MM,
    doors: 2,
    shelves: 2,
    drawers: 0,
    categoria: "base",
  },
  {
    id: "base-1200-3portas-divisor-2prateleiras",
    nome: "A16 120cm 3 portas",
    widthMm: 1200,
    heightMm: BASE_HEIGHT_MM,
    depthMm: BASE_DEPTH_MM,
    doors: 3,
    shelves: 2,
    drawers: 0,
    verticalDivider: true,
    categoria: "base",
  },
  {
    id: "base-1200-canto-direito",
    nome: "A17 120cm 1 porta",
    widthMm: 1200,
    heightMm: BASE_HEIGHT_MM,
    depthMm: BASE_DEPTH_MM,
    doors: 1,
    shelves: 2,
    drawers: 0,
    cornerRight: true,
    categoria: "base",
  },
  {
    id: "base-1200-canto-esquerdo",
    nome: "A18 120cm 1 porta",
    widthMm: 1200,
    heightMm: BASE_HEIGHT_MM,
    depthMm: BASE_DEPTH_MM,
    doors: 1,
    shelves: 2,
    drawers: 0,
    cornerLeft: true,
    categoria: "base",
  },
];
