import type { BaseCabinetModel } from "./types";

/** Altura padrão base (mm). */
const BASE_HEIGHT_MM = 720;
/** Profundidade padrão base (mm). */
const BASE_DEPTH_MM = 600;

/**
 * Modelos base de armários (Base Cabinets).
 * Cada entrada é uma unidade individual; o sistema aplica espessura, costa, pés e regras 32mm.
 */
export const BASE_CABINET_MODELS: BaseCabinetModel[] = [
  {
    id: "base-200-garravera",
    nome: "200mm Garravera",
    widthMm: 200,
    heightMm: 800,
    depthMm: BASE_DEPTH_MM,
    doors: 0,
    shelves: 5,
    drawers: 0,
    categoria: "base",
  },
  {
    id: "base-300-porta-2prateleiras",
    nome: "300mm 1 porta + 2 prateleiras",
    widthMm: 300,
    heightMm: BASE_HEIGHT_MM,
    depthMm: BASE_DEPTH_MM,
    doors: 1,
    shelves: 2,
    drawers: 0,
    categoria: "base",
  },
  {
    id: "base-300-3gavetas",
    nome: "300mm 3 gavetas",
    widthMm: 300,
    heightMm: BASE_HEIGHT_MM,
    depthMm: BASE_DEPTH_MM,
    doors: 0,
    shelves: 0,
    drawers: 3,
    categoria: "base",
  },
  {
    id: "base-400-3gavetas",
    nome: "400mm 3 gavetas",
    widthMm: 400,
    heightMm: BASE_HEIGHT_MM,
    depthMm: BASE_DEPTH_MM,
    doors: 0,
    shelves: 0,
    drawers: 3,
    categoria: "base",
  },
  {
    id: "base-400-porta-3gavetas-2prateleiras",
    nome: "400mm 1 porta + 3 gavetas + 2 prateleiras",
    widthMm: 400,
    heightMm: BASE_HEIGHT_MM,
    depthMm: BASE_DEPTH_MM,
    doors: 1,
    shelves: 2,
    drawers: 3,
    categoria: "base",
  },
  {
    id: "base-500-3gavetas",
    nome: "500mm 3 gavetas",
    widthMm: 500,
    heightMm: BASE_HEIGHT_MM,
    depthMm: BASE_DEPTH_MM,
    doors: 0,
    shelves: 0,
    drawers: 3,
    categoria: "base",
  },
  {
    id: "base-500-porta-2prateleiras",
    nome: "500mm 1 porta + 2 prateleiras",
    widthMm: 500,
    heightMm: BASE_HEIGHT_MM,
    depthMm: BASE_DEPTH_MM,
    doors: 1,
    shelves: 2,
    drawers: 0,
    categoria: "base",
  },
  {
    id: "base-600-2portas-2prateleiras",
    nome: "600mm 2 portas + 2 prateleiras",
    widthMm: 600,
    heightMm: BASE_HEIGHT_MM,
    depthMm: BASE_DEPTH_MM,
    doors: 2,
    shelves: 2,
    drawers: 0,
    categoria: "base",
  },
  {
    id: "base-600-3gavetas",
    nome: "600mm 3 gavetas",
    widthMm: 600,
    heightMm: BASE_HEIGHT_MM,
    depthMm: BASE_DEPTH_MM,
    doors: 0,
    shelves: 0,
    drawers: 3,
    categoria: "base",
  },
  {
    id: "base-700-2portas-2prateleiras",
    nome: "700mm 2 portas + 2 prateleiras",
    widthMm: 700,
    heightMm: BASE_HEIGHT_MM,
    depthMm: BASE_DEPTH_MM,
    doors: 2,
    shelves: 2,
    drawers: 0,
    categoria: "base",
  },
  {
    id: "base-800-2portas-2prateleiras",
    nome: "800mm 2 portas + 2 prateleiras",
    widthMm: 800,
    heightMm: BASE_HEIGHT_MM,
    depthMm: BASE_DEPTH_MM,
    doors: 2,
    shelves: 2,
    drawers: 0,
    categoria: "base",
  },
  {
    id: "base-900-2portas-2prateleiras",
    nome: "900mm 2 portas + 2 prateleiras",
    widthMm: 900,
    heightMm: BASE_HEIGHT_MM,
    depthMm: BASE_DEPTH_MM,
    doors: 2,
    shelves: 2,
    drawers: 0,
    categoria: "base",
  },
  {
    id: "base-1000-2portas-2prateleiras",
    nome: "1000mm 2 portas + 2 prateleiras",
    widthMm: 1000,
    heightMm: BASE_HEIGHT_MM,
    depthMm: BASE_DEPTH_MM,
    doors: 2,
    shelves: 2,
    drawers: 0,
    categoria: "base",
  },
  {
    id: "base-1100-2portas-2prateleiras",
    nome: "1100mm 2 portas + 2 prateleiras",
    widthMm: 1100,
    heightMm: BASE_HEIGHT_MM,
    depthMm: BASE_DEPTH_MM,
    doors: 2,
    shelves: 2,
    drawers: 0,
    categoria: "base",
  },
  {
    id: "base-1200-2portas-2prateleiras",
    nome: "1200mm 2 portas + 2 prateleiras",
    widthMm: 1200,
    heightMm: BASE_HEIGHT_MM,
    depthMm: BASE_DEPTH_MM,
    doors: 2,
    shelves: 2,
    drawers: 0,
    categoria: "base",
  },
  {
    id: "base-1200-3portas-divisor-2prateleiras",
    nome: "1200mm 3 portas + divisor + 2 prateleiras",
    widthMm: 1200,
    heightMm: BASE_HEIGHT_MM,
    depthMm: BASE_DEPTH_MM,
    doors: 3,
    shelves: 2,
    drawers: 0,
    verticalDivider: true,
    categoria: "base",
  },
  {
    id: "base-1200-canto-direito",
    nome: "1200mm canto direito (1 porta + 2 prateleiras)",
    widthMm: 1200,
    heightMm: BASE_HEIGHT_MM,
    depthMm: BASE_DEPTH_MM,
    doors: 1,
    shelves: 2,
    drawers: 0,
    cornerRight: true,
    categoria: "base",
  },
  {
    id: "base-1200-canto-esquerdo",
    nome: "1200mm canto esquerdo (1 porta + 2 prateleiras)",
    widthMm: 1200,
    heightMm: BASE_HEIGHT_MM,
    depthMm: BASE_DEPTH_MM,
    doors: 1,
    shelves: 2,
    drawers: 0,
    cornerLeft: true,
    categoria: "base",
  },
];
